// Built-in words theme. Use naming: { strategy: "words", theme: "aurebesh" }.
// Order is prominence: the first words land on the document shell.
// Aurebesh letter names, then the extra glyphs and sister scripts.

export const AUREBESH_VOCABULARY: ReadonlyArray<string> = [
  "aurek",
  "besh",
  "cresh",
  "dorn",
  "esk",
  "forn",
  "grek",
  "herf",
  "isk",
  "jenth",
  "krill",
  "leth",
  "mern",
  "nern",
  "osk",
  "peth",
  "qek",
  "resh",
  "senth",
  "trill",
  "usk",
  "vev",
  "wesk",
  "xesh",
  "yirt",
  "zerek",
  "cherek",
  "nen",
  "sen",
  "thesh",
  "orenth",
  "aurebesh",
  "highgalactic",
  "sithscript",
  "urkittat",
  "droidbinary",
  "futhork",
  "coremaic",
  "outerim",
  "umbaran",
  "runic",
];
