// Built-in words theme. Use naming: { strategy: "words", theme: "huttese" }.
// Order is prominence: the first words land on the document shell.
// Huttese and Hutt-space slang, already CSS-ident-safe.

export const HUTTESE_VOCABULARY: ReadonlyArray<string> = [
  "ooma",
  "chuba",
  "boska",
  "wanga",
  "jopay",
  "poodoo",
  "schutta",
  "wermo",
  "mooleerah",
  "koochoo",
  "cheeska",
  "bargon",
  "haku",
  "stuka",
  "dewanna",
  "fierfek",
  "murishani",
  "jeedai",
  "nalhutta",
  "kajidic",
  "desilijic",
  "boonta",
  "gardulla",
  "ziro",
  "rotta",
  "gorga",
  "fortuna",
  "salacious",
  "maxrebo",
  "sailbarge",
  "dolpee",
  "tonta",
  "gocola",
  "ateema",
  "ootoowa",
  "tagwa",
  "keelya",
  "dobrah",
  "chongcoya",
  "nuddchaa",
  "huttball",
  "anselma",
  "sleheyron",
  "teth",
  "ronto",
  "dewback",
  "bantha",
  "ephantmon",
  "greedo",
  "sebulba",
  "skiff",
  "palpa",
];
