import { DIALECT_IDS, type DialectId } from "./dialect-ids.js";

// Order: boston, australia, texas, england, scotland, ireland, wales, newyork, canada, savannah, ghetto
const ROWS: Record<string, string[]> = {
  right: [
    "raht",
    "roight",
    "raaaht",
    "roight",
    "richt",
    "roight",
    "ree-ight",
    "roit",
    "right-eh",
    "raaaaaiiiht",
    "rite",
  ],
  left: [
    "left",
    "left",
    "leeeft",
    "left",
    "left",
    "left",
    "lleh-ft",
    "left",
    "left",
    "leeeeeft",
    "lef",
  ],
  center: [
    "centah",
    "centah",
    "ceeen-turrr",
    "centah",
    "centir",
    "centher",
    "cen-tyr",
    "centuh",
    "centaur",
    "ceeeeen-taaaaah",
    "cenna",
  ],
  justify: [
    "justifah",
    "justifoie",
    "jus-taah-fie",
    "justifoie",
    "justifee",
    "justifoie",
    "jus-ti-fy",
    "justifuh",
    "justify-eh",
    "juuuus-taaaah-faaah",
    "jus-a-fy",
  ],
  flex: [
    "flex",
    "flex",
    "fleeeex",
    "flex",
    "flex",
    "flex",
    "fflecks",
    "flex",
    "flex",
    "fleeeeex",
    "flecks",
  ],
  border: [
    "bawdah",
    "bordah",
    "boaah-durrr",
    "bordah",
    "borrdirr",
    "bordher",
    "baw-dyr",
    "bawduh",
    "boar-der",
    "booooah-daaaaah",
    "bowda",
  ],
  hover: [
    "hovah",
    "hovah",
    "hooovurrr",
    "'ovah",
    "hoovirr",
    "hovher",
    "ho-vyr",
    "hovuh",
    "hoaver",
    "hoooo-vuuhh",
    "hovah",
  ],
  order: [
    "awdah",
    "awdah",
    "oar-durrr",
    "awdah",
    "orrrdirr",
    "ordher",
    "aw-dyr",
    "awduh",
    "oar-der",
    "oooah-daaaaah",
    "awda",
  ],
  overflow: [
    "ovahflow",
    "ovahflaow",
    "oovah-flooo",
    "'ovahflow",
    "oovirrfloo",
    "ovverflow",
    "oh-ver-fflow",
    "ovuhflow",
    "oovah-floo",
    "oooovaaaah-flooooow",
    "ovah-flo",
  ],
  container: [
    "containah",
    "containah",
    "c'n-taaaain-urrr",
    "containah",
    "containirr",
    "containher",
    "con-tai-nyr",
    "containuh",
    "container-eh",
    "cuuuhn-taaaaaiiiin-aaaah",
    "c'naina",
  ],
  transparent: [
    "transpahent",
    "transparent",
    "tranz-paaair-int",
    "transpahent",
    "transparent",
    "transparen",
    "trans-par-ent",
    "transpahent",
    "transparent",
    "traaans-paaaair-eeent",
    "transparen",
  ],
  opacity: [
    "opaciteh",
    "opaciteh",
    "oh-paaass-ih-tee",
    "opaciteh",
    "opacitih",
    "opaciteh",
    "oh-pa-ci-ti",
    "opacituh",
    "opacity-eh",
    "ooo-paaah-siiii-teeee",
    "oh-pass-uh-dee",
  ],
  padding: [
    "paddin",
    "paddin",
    "paaaddin",
    "paddin'",
    "paddin",
    "paddin",
    "pad-dio",
    "paddin",
    "padding-eh",
    "paaaadddiiiin'",
    "paddin",
  ],
  bottom: [
    "bottum",
    "bottum",
    "baaaw-tum",
    "bo'um",
    "boattum",
    "bottum",
    "baw-tum",
    "bawdum",
    "bottom",
    "baaaaaw-tuuuum",
    "bawdum",
  ],
  top: [
    "top",
    "top",
    "taawp",
    "top",
    "tawp",
    "top",
    "top",
    "tawp",
    "top",
    "taaaaawp",
    "top",
  ],
  white: [
    "woiht",
    "woight",
    "whaaate",
    "woight",
    "whicht",
    "woight",
    "wh-ite",
    "woit",
    "white-eh",
    "whaaaaaht",
    "wite",
  ],
  black: [
    "black",
    "black",
    "blaaack",
    "black",
    "blrrack",
    "black",
    "bllack",
    "black",
    "black",
    "blaaaack",
    "blaq",
  ],
  light: [
    "laht",
    "loight",
    "laaaht",
    "loight",
    "licht",
    "loight",
    "lleieight",
    "loit",
    "light-eh",
    "laaaaaiiiht",
    "lite",
  ],
  tight: [
    "taht",
    "toight",
    "taaahrt",
    "toight",
    "ticht",
    "toight",
    "teieight",
    "toit",
    "tight-eh",
    "taaaaaiiiht",
    "tite",
  ],
  through: [
    "threw",
    "throo",
    "thruuu",
    "frough",
    "throoch",
    "troo",
    "ddroo",
    "trough",
    "throo",
    "thhhrooooough",
    "fru",
  ],
  stretch: [
    "stretch",
    "stretch",
    "streeetch",
    "stretch",
    "stretch",
    "stretch",
    "stre-tch",
    "stretch",
    "stretch",
    "streeeeetch",
    "estretch",
  ],
  shrink: [
    "shrink",
    "shroink",
    "shreeenk",
    "shrink",
    "shrrink",
    "shrink",
    "shrrink",
    "shrink",
    "shrink",
    "shriiiiink",
    "shwink",
  ],
  grow: [
    "grow",
    "graow",
    "grooow",
    "grow",
    "groo",
    "grow",
    "grrow",
    "grow",
    "groo",
    "grooooow",
    "grow",
  ],
  between: [
    "betweeen",
    "between",
    "buh-tweeeen",
    "between",
    "between",
    "between",
    "be-tween",
    "between",
    "between",
    "beeee-tweeee-eeen",
    "b'tween",
  ],
  around: [
    "araund",
    "araownd",
    "uh-raaaoond",
    "araund",
    "arroond",
    "araund",
    "uh-rround",
    "araund",
    "aroond",
    "uh-raaaaaoooond",
    "around",
  ],
  hidden: [
    "hidden",
    "hidden",
    "hiddden",
    "'idden",
    "hidden",
    "hidden",
    "hid-den",
    "hidden",
    "hidden",
    "hiiiiid-deeeen",
    "hiddin",
  ],
  visible: [
    "visibah",
    "visibah",
    "viz-uh-buuul",
    "visibah",
    "visibir",
    "visibul",
    "vis-ib-yl",
    "visibuh",
    "visible-eh",
    "viiiiiz-uhhhh-buuuul",
    "vizuhbuh",
  ],
  invisible: [
    "invisibah",
    "invisibah",
    "in-viz-uh-buuul",
    "invisibah",
    "invisibir",
    "invisibul",
    "in-vis-ib-yl",
    "invisibuh",
    "invisible-eh",
    "iiiin-viiiiiz-uhhhh-buuuul",
    "invizuhbuh",
  ],
  absolute: [
    "absolute",
    "absolute",
    "ab-suh-luuute",
    "absolute",
    "absolute",
    "absolute",
    "ab-so-lute",
    "absolute",
    "absolute",
    "aaab-soooo-luuuute",
    "abba-loot",
  ],
  relative: [
    "relatahv",
    "relatahv",
    "rell-uh-tiiiv",
    "relatahv",
    "relatirrv",
    "relatav",
    "rel-a-tiv",
    "relatuhv",
    "relative-eh",
    "reeeel-aaaa-tiiiiv",
    "ruh-lidiv",
  ],
  sticky: [
    "sticky",
    "sticky",
    "stiiicky",
    "sticky",
    "sticky",
    "sticky",
    "sti-cky",
    "sticky",
    "sticky",
    "stiiiiicky",
    "esticky",
  ],
  static: [
    "static",
    "static",
    "staaatic",
    "static",
    "static",
    "static",
    "sta-tic",
    "static",
    "static",
    "staaaatic",
    "estattic",
  ],
  translate: [
    "translate",
    "translite",
    "tranz-laaate",
    "translate",
    "translate",
    "translate",
    "trans-llate",
    "translate",
    "translate",
    "traaans-laaaate",
    "tranzlate",
  ],
  rotate: [
    "rotate",
    "rotite",
    "roo-taaate",
    "rotate",
    "rotate",
    "rotate",
    "ro-tate",
    "rotate",
    "rotate",
    "roooo-taaaate",
    "rotate",
  ],
  scale: [
    "scale",
    "skile",
    "skaaale",
    "scale",
    "scale",
    "scale",
    "sca-lle",
    "scale",
    "scale",
    "scaaaale",
    "escale",
  ],
  shadow: [
    "shadow",
    "shadaow",
    "shaaadow",
    "shadow",
    "shadoo",
    "shadow",
    "sha-dow",
    "shadow",
    "shadoo",
    "shaaaadoooow",
    "shadda",
  ],
  outline: [
    "ahtline",
    "aowtloine",
    "owt-laaan",
    "'ahtloine",
    "ootline",
    "outloine",
    "owt-lline",
    "awtline",
    "ootline",
    "ooooot-laaaaahn",
    "out-line",
  ],
  underline: [
    "undahline",
    "undahloine",
    "un-durr-laaan",
    "undahloine",
    "undirrline",
    "undherloine",
    "un-der-lline",
    "unduhline",
    "underline-eh",
    "uuuun-daaaaah-laaaaahn",
    "unna-line",
  ],
  uppercase: [
    "uppahcase",
    "uppahcise",
    "up-purr-caase",
    "uppahcise",
    "uppirrcise",
    "uppahcase",
    "up-per-case",
    "uppuhcase",
    "uppercase-eh",
    "uuuup-aaaah-caaaase",
    "uppa-case",
  ],
  lowercase: [
    "lowahcase",
    "lowaahcise",
    "lo-wurr-caase",
    "lowahcise",
    "looorrcise",
    "lowahcase",
    "llo-wer-case",
    "lowuhcase",
    "lowercase-eh",
    "loooo-aaaah-caaaase",
    "loca-case",
  ],
  capitalize: [
    "capitalahze",
    "capitalahze",
    "cap-ih-tull-ahze",
    "capitalahze",
    "capitalahze",
    "capitalahze",
    "cap-i-tal-ize",
    "capitaluhze",
    "capitalize-eh",
    "caaap-ih-taaaal-aaaaize",
    "capiduh-lize",
  ],
  truncate: [
    "truncat",
    "truncite",
    "trunk-aaate",
    "truncite",
    "truncate",
    "truncate",
    "trun-cate",
    "truncut",
    "truncate",
    "truuuunk-aaate",
    "trunkate",
  ],
  antialiased: [
    "antialiasd",
    "antialiased",
    "an-tee-al-ee-ast",
    "antialiased",
    "antialiased",
    "antialiased",
    "an-ti-al-iased",
    "antialiased",
    "antialiased-eh",
    "aaaan-teeee-aaaal-eeee-aaased",
    "anti-aliced",
  ],
  placeholder: [
    "placeholdah",
    "placeholdah",
    "place-hooold-urrr",
    "placeholdah",
    "placeholdirr",
    "placeholdher",
    "place-hol-dyr",
    "placeholduh",
    "placeholder-eh",
    "plaaace-hooooold-aaaah",
    "place-holda",
  ],
  appearance: [
    "appeahance",
    "appeahance",
    "uh-peer-ints",
    "'appeahance",
    "appeerrance",
    "appeerance",
    "ap-pear-ence",
    "appeeuhance",
    "appearance-eh",
    "uh-peeeeer-aaance",
    "uh-peer-unts",
  ],
  pointer: [
    "pointah",
    "pointah",
    "poynt-urrr",
    "pointah",
    "pointirr",
    "pointher",
    "poin-tyr",
    "pointuh",
    "pointer-eh",
    "pooooiiin-taaaah",
    "pointa",
  ],
  cursor: [
    "cursah",
    "cursah",
    "currr-surrr",
    "cursah",
    "currrsirr",
    "cursher",
    "cur-syr",
    "cawsuh",
    "cursor-eh",
    "cuuuur-saaaah",
    "cursah",
  ],
  default: [
    "default",
    "default",
    "dee-fawwlt",
    "default",
    "default",
    "default",
    "de-fault",
    "default",
    "default",
    "deeee-faaaaawlt",
    "default",
  ],
  allowed: [
    "allowed",
    "allaowed",
    "uh-laaaoowed",
    "'allowed",
    "alloowed",
    "allowed",
    "al-lowed",
    "awlowed",
    "alloowed",
    "uh-laaaaaooooowed",
    "allowd",
  ],
  screen: [
    "screen",
    "screen",
    "screeeen",
    "screen",
    "screen",
    "screen",
    "scre-en",
    "screen",
    "screen",
    "screeee-eeen",
    "escreen",
  ],
  scroll: [
    "scrawl",
    "scroll",
    "scraaawl",
    "scroll",
    "scroall",
    "scroll",
    "scrroll",
    "scrawl",
    "scroll",
    "scroooooll",
    "escroll",
  ],
  overscroll: [
    "ovahscrawl",
    "ovahscroll",
    "oovah-scraaawl",
    "'ovahscroll",
    "oovirrscroall",
    "ovverscroll",
    "oh-ver-scrroll",
    "ovuhscrawl",
    "oovah-scroll",
    "oooovaaaah-scroooooll",
    "ovah-escroll",
  ],
  content: [
    "content",
    "content",
    "cawn-tent",
    "content",
    "content",
    "content",
    "con-tent",
    "cawntent",
    "content",
    "caaaawn-teeent",
    "content",
  ],
  contents: [
    "contents",
    "contents",
    "cawn-tents",
    "contents",
    "contents",
    "contents",
    "con-tents",
    "cawntents",
    "contents",
    "caaaawn-teeents",
    "contents",
  ],
  separate: [
    "sepahate",
    "sepahate",
    "sep-uh-raaate",
    "sepahate",
    "separrate",
    "seperate",
    "sep-a-rate",
    "sepahate",
    "separate-eh",
    "seeee-puuuh-raaaate",
    "esepuh-rate",
  ],
  collapse: [
    "collapse",
    "collapse",
    "cuh-laaapse",
    "collapse",
    "collapse",
    "collapse",
    "col-llapse",
    "cawlapse",
    "collapse",
    "cuh-laaaapse",
    "c'lapse",
  ],
  reverse: [
    "revahse",
    "revahse",
    "ruh-vuurrrse",
    "revahse",
    "revirrse",
    "revherse",
    "re-ver-se",
    "revuhse",
    "reverse-eh",
    "reeee-vuuhhhse",
    "revuss",
  ],
  divide: [
    "divide",
    "divoide",
    "duh-vaaahd",
    "divoide",
    "divide",
    "divoide",
    "di-vide",
    "divide",
    "divide",
    "diiii-vaaaahd",
    "divahd",
  ],
  double: [
    "doubah",
    "dowbah",
    "duuub-ull",
    "doubah",
    "doobir",
    "doubul",
    "dow-byl",
    "doubuh",
    "dooble",
    "duuuu-buuuul",
    "dubble",
  ],
  dotted: [
    "dotted",
    "dotted",
    "daaaw-did",
    "do'ed",
    "dotted",
    "dotted",
    "dot-ted",
    "dawded",
    "dotted",
    "daaaaaw-diiid",
    "dawdid",
  ],
  dashed: [
    "dashed",
    "dashed",
    "daaasht",
    "dashed",
    "dashed",
    "dashed",
    "da-shed",
    "dashed",
    "dashed",
    "daaaasht",
    "dasht",
  ],
  solid: [
    "solid",
    "solid",
    "saw-lid",
    "solid",
    "solid",
    "solid",
    "so-lid",
    "sawlid",
    "solid",
    "soooo-liiud",
    "sawlid",
  ],
  gradient: [
    "gradient",
    "gredient",
    "gray-dee-int",
    "gredient",
    "gredient",
    "gredient",
    "gray-di-ent",
    "gredient",
    "gradient-eh",
    "graaaay-deeee-eeent",
    "gray-dee-int",
  ],
  purple: [
    "puhple",
    "puhple",
    "puuurr-pull",
    "puhple",
    "purrpir",
    "purple",
    "pur-pyl",
    "poiple",
    "purple",
    "puuuur-puuuul",
    "purp",
  ],
  orange: [
    "ahange",
    "orange",
    "oar-aaange",
    "'orange",
    "orrange",
    "orange",
    "or-ange",
    "awrange",
    "orange",
    "oooaaar-aaange",
    "aranj",
  ],
  yellow: [
    "yellah",
    "yellaow",
    "yellll-oh",
    "yellah",
    "yelloor",
    "yellah",
    "yel-low",
    "yelluh",
    "yello",
    "yeeeel-looooow",
    "yella",
  ],
  indigo: [
    "indigo",
    "indigo",
    "in-dee-gooo",
    "indigo",
    "indigo",
    "indigo",
    "in-di-go",
    "indigo",
    "indigo",
    "iiiin-deeee-goooo",
    "in-dee-go",
  ],
  pink: [
    "pink",
    "pink",
    "peeenk",
    "pink",
    "pink",
    "pink",
    "pink",
    "pink",
    "pink",
    "piiiink",
    "pink",
  ],
  green: [
    "green",
    "green",
    "greeeen",
    "green",
    "green",
    "green",
    "grreen",
    "green",
    "green",
    "greeeeen",
    "green",
  ],
  blue: [
    "blue",
    "bloo",
    "bloooo",
    "blue",
    "bloo",
    "blue",
    "bllue",
    "blue",
    "bloo",
    "bluuuue",
    "bloo",
  ],
  gray: [
    "gray",
    "grie",
    "graaay",
    "gray",
    "gray",
    "gray",
    "gray",
    "gray",
    "gray",
    "graaaay",
    "gray",
  ],
  teal: [
    "teal",
    "teel",
    "teeeel",
    "teal",
    "teal",
    "teal",
    "teal",
    "teal",
    "teal",
    "teeeeel",
    "teal",
  ],
  red: [
    "red",
    "red",
    "reeed",
    "red",
    "rrred",
    "red",
    "rred",
    "red",
    "red",
    "reeeed",
    "red",
  ],
  current: [
    "currant",
    "currant",
    "currr-int",
    "currant",
    "currrint",
    "currant",
    "cur-rent",
    "cawrent",
    "current-eh",
    "cuuuur-eeent",
    "curren",
  ],
  cover: [
    "covah",
    "covah",
    "cuh-vurrr",
    "covah",
    "covirr",
    "covher",
    "co-vyr",
    "covuh",
    "cover-eh",
    "cuuuh-vuuhhh",
    "cova",
  ],
  contain: [
    "contain",
    "contain",
    "c'n-taaaain",
    "contain",
    "contain",
    "contain",
    "con-tain",
    "contain",
    "contain",
    "cuuuhn-taaaaain",
    "c'nain",
  ],
  repeat: [
    "repeat",
    "repite",
    "ree-peeeet",
    "repeat",
    "repeat",
    "repeat",
    "re-peat",
    "repeat",
    "repeat",
    "reeee-peeeeet",
    "repeat",
  ],
  space: [
    "space",
    "spice",
    "spaaace",
    "space",
    "space",
    "space",
    "spa-ce",
    "space",
    "space",
    "spaaaace",
    "espace",
  ],
  round: [
    "raund",
    "raownd",
    "raaaoond",
    "raund",
    "rroond",
    "raund",
    "rround",
    "raund",
    "roond",
    "raaaaaoooond",
    "roun",
  ],
  linear: [
    "lineah",
    "lineah",
    "line-urrr",
    "lineah",
    "lineirr",
    "lineher",
    "llin-ear",
    "lineuh",
    "linear-eh",
    "liiiin-eeeaaah",
    "linea",
  ],
  duration: [
    "durashun",
    "durashun",
    "duu-ray-shun",
    "durashun",
    "durrashun",
    "durashun",
    "dur-a-shun",
    "durashun",
    "duration-eh",
    "duuuu-raaaay-shuuun",
    "durashun",
  ],
  delay: [
    "delay",
    "delie",
    "duh-laaay",
    "delay",
    "delay",
    "delay",
    "de-llay",
    "delay",
    "delay",
    "deeee-laaaay",
    "delay",
  ],
  transition: [
    "transishun",
    "transishun",
    "tranz-ish-un",
    "transishun",
    "transishun",
    "transishun",
    "tran-si-shun",
    "transishun",
    "transition-eh",
    "traaans-iiii-shuuun",
    "tranzishun",
  ],
  animate: [
    "animate",
    "animite",
    "an-ih-maaate",
    "animate",
    "animate",
    "animate",
    "an-i-mate",
    "animate",
    "animate",
    "aaaan-ih-maaaate",
    "anuhmate",
  ],
  bounce: [
    "bounce",
    "baownce",
    "baaaoonce",
    "bounce",
    "boonce",
    "bounce",
    "bounce",
    "bounce",
    "boonce",
    "baaaaaooonce",
    "bounce",
  ],
  pulse: [
    "pulse",
    "pulse",
    "puuulse",
    "pulse",
    "pulse",
    "pulse",
    "pulse",
    "pulse",
    "pulse",
    "puuuulse",
    "pulse",
  ],
  spin: [
    "spin",
    "spin",
    "speeen",
    "spin",
    "spin",
    "spin",
    "spin",
    "spin",
    "spin",
    "spiiiin",
    "espin",
  ],
  ping: [
    "ping",
    "ping",
    "peeen",
    "ping",
    "ping",
    "ping",
    "pio",
    "ping",
    "ping-eh",
    "piiiin'",
    "pin",
  ],
  ease: [
    "ease",
    "eeze",
    "eeeeze",
    "ease",
    "ease",
    "ease",
    "ease",
    "ease",
    "ease",
    "eeeease",
    "eeze",
  ],
  none: [
    "none",
    "naun",
    "nooone",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "nooooone",
    "none",
  ],
  auto: [
    "auto",
    "auto",
    "aww-toe",
    "auto",
    "auto",
    "auto",
    "au-to",
    "awto",
    "auto",
    "aaaaaw-toooo",
    "auto",
  ],
  fixed: [
    "fixed",
    "fixed",
    "fiixed",
    "fixed",
    "fixed",
    "fixed",
    "fi-xed",
    "fixed",
    "fixed",
    "fiiiiixed",
    "fickst",
  ],
  local: [
    "local",
    "local",
    "lo-cull",
    "local",
    "local",
    "local",
    "llo-cal",
    "lawcal",
    "local",
    "loooo-caaaal",
    "local",
  ],
  clip: [
    "clip",
    "clip",
    "cleeep",
    "clip",
    "clip",
    "clip",
    "clip",
    "clip",
    "clip",
    "cliiiip",
    "clip",
  ],
  text: [
    "text",
    "text",
    "teeeext",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "teeeeext",
    "tex",
  ],
  mb: [
    "emb",
    "em-bee",
    "emmm-beee",
    "em-bee",
    "emb",
    "em-bee",
    "em-bee",
    "em-bee",
    "em-bee",
    "emmmm-beeeee",
    "embay",
  ],
  mr: [
    "em-ah",
    "em-ah",
    "emmm-arrr",
    "em-ah",
    "em-rrr",
    "em-r",
    "em-yr",
    "em-uh",
    "em-ar",
    "emmmm-arrrrr",
    "em-arr",
  ],
  mt: [
    "em-tee",
    "em-tee",
    "emmm-teee",
    "em-tee",
    "em-tee",
    "em-tee",
    "em-tee",
    "em-tee",
    "em-tee",
    "emmmm-teeeee",
    "em-tee",
  ],
  ml: [
    "em-ell",
    "em-ell",
    "emmm-ellll",
    "em-ell",
    "em-ell",
    "em-ell",
    "em-ell",
    "em-ell",
    "em-ell",
    "emmmm-elllll",
    "em-ell",
  ],
  mx: [
    "em-ecks",
    "em-ecks",
    "emmm-ecks",
    "em-ecks",
    "em-ecks",
    "em-ecks",
    "em-ecks",
    "em-ecks",
    "em-ecks",
    "emmmm-eeecks",
    "em-ecks",
  ],
  my: [
    "em-why",
    "em-why",
    "emmm-whyyy",
    "em-why",
    "em-why",
    "em-why",
    "em-why",
    "em-why",
    "em-why",
    "emmmm-whyyyy",
    "em-why",
  ],
  pb: [
    "pee-bee",
    "pee-bee",
    "peee-beee",
    "pee-bee",
    "pee-bee",
    "pee-bee",
    "pee-bee",
    "pee-bee",
    "pee-bee",
    "peeee-beeeee",
    "peebee",
  ],
  pr: [
    "pee-ah",
    "pee-ah",
    "peee-arrr",
    "pee-ah",
    "pee-rrr",
    "pee-r",
    "pee-yr",
    "pee-uh",
    "pee-ar",
    "peeee-arrrrr",
    "pee-arr",
  ],
  pt: [
    "pee-tee",
    "pee-tee",
    "peee-teee",
    "pee-tee",
    "pee-tee",
    "pee-tee",
    "pee-tee",
    "pee-tee",
    "pee-tee",
    "peeee-teeeee",
    "pee-tee",
  ],
  pl: [
    "pee-ell",
    "pee-ell",
    "peee-ellll",
    "pee-ell",
    "pee-ell",
    "pee-ell",
    "pee-ell",
    "pee-ell",
    "pee-ell",
    "peeee-elllll",
    "pee-ell",
  ],
  px: [
    "pee-ecks",
    "pee-ecks",
    "peee-ecks",
    "pee-ecks",
    "pee-ecks",
    "pee-ecks",
    "pee-ecks",
    "pee-ecks",
    "pee-ecks",
    "peeee-eeecks",
    "pee-ecks",
  ],
  py: [
    "pee-why",
    "pee-why",
    "peee-whyyy",
    "pee-why",
    "pee-why",
    "pee-why",
    "pee-why",
    "pee-why",
    "pee-why",
    "peeee-whyyyy",
    "pee-why",
  ],
  bg: [
    "bee-gee",
    "bee-gee",
    "beee-geee",
    "bee-gee",
    "bee-gee",
    "bee-gee",
    "bee-gee",
    "bee-gee",
    "bee-gee",
    "beeeee-geeeee",
    "beegee",
  ],
  bl: [
    "bee-ell",
    "bee-ell",
    "beee-ellll",
    "bee-ell",
    "bee-ell",
    "bee-ell",
    "bll",
    "bee-ell",
    "bee-ell",
    "beeeee-elllll",
    "bee-ell",
  ],
  br: [
    "bee-ah",
    "bee-ah",
    "beee-arrr",
    "bee-ah",
    "bee-rrr",
    "bee-r",
    "bee-yr",
    "bee-uh",
    "bee-ar",
    "beeeee-arrrrr",
    "bee-arr",
  ],
  tl: [
    "tee-ell",
    "tee-ell",
    "teee-ellll",
    "tee-ell",
    "tee-ell",
    "tee-ell",
    "tee-ell",
    "tee-ell",
    "tee-ell",
    "teeeee-elllll",
    "tee-ell",
  ],
  tr: [
    "tee-ah",
    "tee-ah",
    "teee-arrr",
    "tee-ah",
    "tee-rrr",
    "tee-r",
    "tee-yr",
    "tee-uh",
    "tee-ar",
    "teeeee-arrrrr",
    "tee-arr",
  ],
  xs: [
    "ex-ess",
    "ex-ess",
    "eeeex-esss",
    "ex-ess",
    "ex-ess",
    "ex-ess",
    "ex-ess",
    "ex-ess",
    "ex-ess",
    "eeeeex-eeesss",
    "ecks-ess",
  ],
  sm: [
    "ess-em",
    "ess-em",
    "esss-emmm",
    "ess-em",
    "ess-em",
    "ess-em",
    "ess-em",
    "ess-em",
    "ess-em",
    "eeesss-emmmm",
    "essem",
  ],
  md: [
    "em-dee",
    "em-dee",
    "emmm-deee",
    "em-dee",
    "em-dee",
    "em-dee",
    "em-dee",
    "em-dee",
    "em-dee",
    "emmmm-deeeee",
    "emdee",
  ],
  lg: [
    "ell-gee",
    "ell-gee",
    "ellll-geee",
    "ell-gee",
    "ell-gee",
    "ell-gee",
    "ell-gee",
    "ell-gee",
    "ell-gee",
    "elllll-geeeee",
    "ellgee",
  ],
  xl: [
    "ecks-ell",
    "ecks-ell",
    "ecks-ellll",
    "ecks-ell",
    "ecks-ell",
    "ecks-ell",
    "ecks-ell",
    "ecks-ell",
    "ecks-ell",
    "eeecks-elllll",
    "ecksell",
  ],
  start: [
    "staht",
    "staht",
    "staaahrt",
    "staht",
    "stairrt",
    "staht",
    "sta-rt",
    "staht",
    "start",
    "staaaahrt",
    "estart",
  ],
  end: [
    "end",
    "end",
    "eeend",
    "end",
    "end",
    "end",
    "end",
    "end",
    "end",
    "eeeend",
    "end",
  ],
  evenly: [
    "evenleh",
    "evenleh",
    "ee-vun-leee",
    "evenleh",
    "evenleh",
    "evenleh",
    "e-ven-ly",
    "evenluh",
    "evenly-eh",
    "eeee-vuuun-leeee",
    "evenlee",
  ],
  wrap: [
    "wrap",
    "wrap",
    "wraaap",
    "wrap",
    "wrap",
    "wrap",
    "wrap",
    "wrap",
    "wrap",
    "wraaaap",
    "rap",
  ],
  nowrap: [
    "nowrap",
    "nowrap",
    "no-wraaap",
    "nowrap",
    "nowrap",
    "nowrap",
    "no-wrap",
    "nowrap",
    "nowrap",
    "noooo-wraaaap",
    "no-rap",
  ],
  items: [
    "items",
    "items",
    "eye-tums",
    "items",
    "items",
    "items",
    "i-tems",
    "items",
    "items",
    "iii-tuuums",
    "items",
  ],
  self: [
    "self",
    "self",
    "seeelf",
    "self",
    "self",
    "self",
    "self",
    "self",
    "self",
    "seeeelf",
    "eself",
  ],
  inline: [
    "inline",
    "inloine",
    "in-laaan",
    "inloine",
    "inline",
    "inloine",
    "in-lline",
    "inline",
    "inline",
    "iiiin-laaaaahn",
    "inline",
  ],
  block: [
    "block",
    "block",
    "blaaawk",
    "block",
    "block",
    "block",
    "bllock",
    "blawk",
    "block",
    "blaaaawk",
    "blawk",
  ],
  grid: [
    "grid",
    "grid",
    "greeed",
    "grid",
    "grrid",
    "grid",
    "grrid",
    "grid",
    "grid",
    "greeeed",
    "grid",
  ],
  flow: [
    "flow",
    "flaow",
    "floooow",
    "flow",
    "floo",
    "flow",
    "fflow",
    "flow",
    "floo",
    "flooooow",
    "flo",
  ],
  root: [
    "root",
    "root",
    "rooooot",
    "root",
    "root",
    "root",
    "rroot",
    "root",
    "root",
    "roooooot",
    "root",
  ],
  row: [
    "row",
    "raow",
    "roooo",
    "row",
    "roo",
    "row",
    "rrow",
    "row",
    "roo",
    "rooooow",
    "row",
  ],
  col: [
    "cawl",
    "col",
    "cawwll",
    "col",
    "col",
    "col",
    "col",
    "cawl",
    "col",
    "caaaawl",
    "cawl",
  ],
  initial: [
    "initial",
    "initial",
    "ih-nish-ull",
    "inishul",
    "initial",
    "initial",
    "i-ni-tial",
    "inishul",
    "initial-eh",
    "ih-niiiiish-uuuul",
    "inishul",
  ],
  focus: [
    "focus",
    "focus",
    "foe-cuss",
    "focus",
    "focus",
    "focus",
    "fo-cus",
    "focus",
    "focus",
    "foooo-cuuuss",
    "focus",
  ],
  within: [
    "within",
    "within",
    "wih-thiiin",
    "wifin",
    "within",
    "witin",
    "wi-ddin",
    "widin",
    "within",
    "wiiii-thhhiiiin",
    "widin",
  ],
  span: [
    "span",
    "span",
    "spaaaan",
    "span",
    "span",
    "span",
    "span",
    "span",
    "span",
    "spaaaaan",
    "espan",
  ],
  gap: [
    "gap",
    "gap",
    "gaaap",
    "gap",
    "gap",
    "gap",
    "gap",
    "gap",
    "gap",
    "gaaaap",
    "gap",
  ],
  rows: [
    "rows",
    "raows",
    "rooows",
    "rows",
    "roos",
    "rows",
    "rrows",
    "rows",
    "roos",
    "rooooows",
    "rows",
  ],
  cols: [
    "cawls",
    "cols",
    "cawwlls",
    "cols",
    "cols",
    "cols",
    "cols",
    "cawls",
    "cols",
    "caaaawls",
    "cawls",
  ],
  dense: [
    "dense",
    "dense",
    "deeeense",
    "dense",
    "dense",
    "dense",
    "dense",
    "dense",
    "dense",
    "deeeeense",
    "dense",
  ],
  max: [
    "max",
    "max",
    "maaax",
    "max",
    "max",
    "max",
    "max",
    "max",
    "max",
    "maaaax",
    "macks",
  ],
  min: [
    "min",
    "min",
    "meeen",
    "min",
    "min",
    "min",
    "min",
    "min",
    "min",
    "miiiin",
    "min",
  ],
  full: [
    "full",
    "full",
    "fuuull",
    "full",
    "full",
    "full",
    "ffull",
    "full",
    "full",
    "fuuuull",
    "full",
  ],
  place: [
    "place",
    "plice",
    "plaaace",
    "place",
    "place",
    "place",
    "pll-ace",
    "place",
    "place",
    "plaaaace",
    "place",
  ],
  group: [
    "group",
    "growp",
    "grooop",
    "group",
    "groop",
    "group",
    "grroup",
    "group",
    "groop",
    "grooooop",
    "group",
  ],
  list: [
    "list",
    "list",
    "leeeest",
    "list",
    "list",
    "list",
    "llist",
    "list",
    "list",
    "liiiist",
    "list",
  ],
  outside: [
    "ahtside",
    "aowtside",
    "owt-saahd",
    "'ahtsoide",
    "ootside",
    "outsoide",
    "owt-side",
    "awtside",
    "ootside",
    "ooooot-saaaahd",
    "out-side",
  ],
  lining: [
    "linin",
    "loinin",
    "laaan-in",
    "loinin'",
    "linin",
    "loinin",
    "llin-io",
    "linin",
    "lining-eh",
    "laaaaahn-iiiin'",
    "linin",
  ],
  nums: [
    "nums",
    "nums",
    "nuuums",
    "nums",
    "nums",
    "nums",
    "nums",
    "nums",
    "nums",
    "nuuuums",
    "nums",
  ],
  normal: [
    "nawmal",
    "normal",
    "naww-mull",
    "normal",
    "normal",
    "normal",
    "nor-mal",
    "nawmul",
    "normal",
    "naaaaw-muuul",
    "nawmuh",
  ],
  oldstyle: [
    "owldstyle",
    "owldstoile",
    "oll-staaahl",
    "owldstoile",
    "owldstyle",
    "owldstoile",
    "owld-style",
    "owldstyle",
    "oldstyle",
    "oooold-styyyyyle",
    "ol-style",
  ],
  stacked: [
    "stacked",
    "stacked",
    "staaacked",
    "stacked",
    "stacked",
    "stacked",
    "sta-cked",
    "stacked",
    "stacked",
    "staaaacked",
    "estacked",
  ],
  fractions: [
    "fracshuns",
    "fracshuns",
    "frack-shuns",
    "fracshuns",
    "frrracshuns",
    "fracshuns",
    "frac-shuns",
    "fracshuns",
    "fractions-eh",
    "fraaaack-shuuuns",
    "frackshuns",
  ],
  align: [
    "align",
    "align",
    "uh-laaan",
    "align",
    "align",
    "align",
    "a-llign",
    "align",
    "align",
    "uh-laaaaahn",
    "align",
  ],
  clear: [
    "cleah",
    "cleah",
    "cleeeer",
    "cleah",
    "cleerr",
    "cleaher",
    "cllear",
    "cleeuh",
    "clear",
    "cleeeeaaah",
    "clea",
  ],
  both: [
    "both",
    "both",
    "booooth",
    "bof",
    "both",
    "bot",
    "bodd",
    "bod",
    "both",
    "booooothhh",
    "bof",
  ],
  clearfix: [
    "cleahfix",
    "cleahfix",
    "cleeeer-fix",
    "cleahfix",
    "cleerrfix",
    "cleaherfix",
    "cllear-fix",
    "cleeuhfix",
    "clearfix",
    "cleeeeaaah-fiiiix",
    "clea-ficks",
  ],
  float: [
    "float",
    "float",
    "floooat",
    "float",
    "float",
    "float",
    "ffloat",
    "float",
    "float",
    "flooooat",
    "float",
  ],
  inset: [
    "inset",
    "inset",
    "in-seet",
    "inset",
    "inset",
    "inset",
    "in-set",
    "inset",
    "inset",
    "iiiin-seeeet",
    "inset",
  ],
  object: [
    "object",
    "object",
    "awb-ject",
    "object",
    "object",
    "object",
    "ob-ject",
    "awbject",
    "object",
    "aaaawb-jeeeect",
    "object",
  ],
  skew: [
    "skew",
    "skyoo",
    "skyooo",
    "skew",
    "skew",
    "skew",
    "skew",
    "skew",
    "skew",
    "skyyyyooo",
    "eskyoo",
  ],
  baseline: [
    "baseline",
    "baseloine",
    "base-laaan",
    "baseloine",
    "baseline",
    "baseloine",
    "base-lline",
    "baseline",
    "baseline",
    "baaaase-laaaaahn",
    "baseline",
  ],
  middle: [
    "middah",
    "middah",
    "mid-ull",
    "middah",
    "middir",
    "middul",
    "mid-dyl",
    "midduh",
    "middle-eh",
    "miiii-duuuul",
    "midduh",
  ],
  ring: [
    "ring",
    "ring",
    "reeeng",
    "ring",
    "rring",
    "ring",
    "rrio",
    "ring",
    "ring-eh",
    "riiiin'",
    "ring",
  ],
  offset: [
    "awfset",
    "offset",
    "awff-set",
    "offset",
    "offset",
    "offset",
    "off-set",
    "awfset",
    "offset",
    "aaaawf-seeeet",
    "offset",
  ],
  inner: [
    "innah",
    "innah",
    "inn-urrr",
    "innah",
    "innirr",
    "innher",
    "in-nyr",
    "innuh",
    "inner-eh",
    "iiiinn-aaaah",
    "inna",
  ],
  fill: [
    "fill",
    "fill",
    "feeeel",
    "fill",
    "fill",
    "fill",
    "ffill",
    "fill",
    "fill",
    "fiiiill",
    "fill",
  ],
  stroke: [
    "stroke",
    "stroke",
    "stroooke",
    "stroke",
    "stroke",
    "stroke",
    "strroke",
    "stroke",
    "stroke",
    "stroooooke",
    "estroke",
  ],
  table: [
    "tabah",
    "tabah",
    "tay-bull",
    "tabah",
    "tabir",
    "tabul",
    "ta-byl",
    "tabuh",
    "table-eh",
    "taaaay-buuuul",
    "tabuh",
  ],
  caption: [
    "capshun",
    "capshun",
    "cap-shun",
    "capshun",
    "capshun",
    "capshun",
    "cap-shun",
    "capshun",
    "caption-eh",
    "caaap-shuuun",
    "capshun",
  ],
  cell: [
    "cell",
    "cell",
    "ceeeel",
    "cell",
    "cell",
    "cell",
    "cell",
    "cell",
    "cell",
    "ceeeell",
    "cell",
  ],
  column: [
    "cawlum",
    "column",
    "caww-lum",
    "column",
    "column",
    "column",
    "col-umn",
    "cawlum",
    "column",
    "caaaaw-luuuum",
    "cawlum",
  ],
  footer: [
    "footah",
    "footah",
    "foooot-urrr",
    "footah",
    "footirr",
    "foother",
    "foo-tyr",
    "footuh",
    "footer-eh",
    "foooooot-aaaah",
    "foota",
  ],
  header: [
    "headah",
    "headah",
    "hee-durrr",
    "'eadah",
    "headirr",
    "headher",
    "hea-dyr",
    "headuh",
    "header-eh",
    "heeee-daaaaah",
    "heada",
  ],
  subpixel: [
    "subpixel",
    "subpixel",
    "sub-pix-ull",
    "subpixel",
    "subpixel",
    "subpixel",
    "sub-pix-yl",
    "subpixel",
    "subpixel",
    "suuub-piiiix-uuuul",
    "subpixuh",
  ],
  break: [
    "break",
    "breik",
    "braaayk",
    "break",
    "brreak",
    "break",
    "brreak",
    "break",
    "break",
    "braaaaayk",
    "break",
  ],
  words: [
    "wuds",
    "wuds",
    "wuuurds",
    "wuds",
    "wirrds",
    "wuds",
    "worrds",
    "wuds",
    "words",
    "wuuuuurds",
    "wuds",
  ],
  all: [
    "awl",
    "awl",
    "awwll",
    "awl",
    "all",
    "awl",
    "all",
    "awl",
    "all",
    "aaaaawl",
    "awl",
  ],
  case: [
    "case",
    "cise",
    "caaaase",
    "case",
    "case",
    "case",
    "case",
    "case",
    "case",
    "caaaase",
    "case",
  ],
  leading: [
    "leadin",
    "leadin",
    "leee-din",
    "leadin'",
    "leadin",
    "leadin",
    "llead-io",
    "leadin",
    "leading-eh",
    "leeee-diiiin'",
    "leadin",
  ],
  snug: [
    "snug",
    "snug",
    "snuuug",
    "snug",
    "snug",
    "snug",
    "snug",
    "snug",
    "snug",
    "snuuuug",
    "es-nug",
  ],
  relaxed: [
    "relaxed",
    "relaxed",
    "ruh-laaaxed",
    "relaxed",
    "relaxed",
    "relaxed",
    "re-llaxed",
    "relaxed",
    "relaxed",
    "reeee-laaaaxed",
    "relax",
  ],
  loose: [
    "loose",
    "loose",
    "loooose",
    "loose",
    "loose",
    "loose",
    "lloose",
    "loose",
    "loose",
    "looooose",
    "loose",
  ],
  line: [
    "line",
    "loine",
    "laaan",
    "loine",
    "line",
    "loine",
    "lline",
    "line",
    "line",
    "laaaaahn",
    "line",
  ],
  font: [
    "font",
    "font",
    "faaawnt",
    "font",
    "font",
    "font",
    "font",
    "fawnt",
    "font",
    "faaaaawnt",
    "font",
  ],
  hairline: [
    "heahline",
    "heahloine",
    "hair-laaan",
    "'eahloine",
    "hairline",
    "hairloine",
    "hair-lline",
    "heahline",
    "hairline",
    "haaaair-laaaaahn",
    "hairline",
  ],
  thin: [
    "thin",
    "thin",
    "theeen",
    "fin",
    "thin",
    "tin",
    "ddin",
    "din",
    "thin",
    "thhhiiiin",
    "tin",
  ],
  medium: [
    "medium",
    "medium",
    "mee-dee-um",
    "medium",
    "medium",
    "medium",
    "me-di-um",
    "medium",
    "medium",
    "meeee-deeee-uuuum",
    "medium",
  ],
  semibold: [
    "semibowld",
    "semibowld",
    "semi-bollld",
    "semibowld",
    "semibold",
    "semibowld",
    "semi-bold",
    "semibold",
    "semibold",
    "seeee-miiii-boooold",
    "semi-bol",
  ],
  bold: [
    "bowld",
    "bowld",
    "bollld",
    "bowld",
    "bold",
    "bowld",
    "bold",
    "bold",
    "bold",
    "boooold",
    "bol",
  ],
  extrabold: [
    "extahbowld",
    "extahbowld",
    "ex-truh-bollld",
    "extahbowld",
    "extrabold",
    "extahbowld",
    "ex-tra-bold",
    "extruhbold",
    "extrabold",
    "eeeex-traaaah-boooold",
    "eckstra-bol",
  ],
  extralight: [
    "extahlaht",
    "extahloight",
    "ex-truh-laaaht",
    "extahloight",
    "extralicht",
    "extahloight",
    "ex-tra-lleieight",
    "extruhlight",
    "extralight",
    "eeeex-traaaah-laaaaaiiiht",
    "eckstra-lite",
  ],
  base: [
    "base",
    "bise",
    "baaaase",
    "base",
    "base",
    "base",
    "base",
    "base",
    "base",
    "baaaase",
    "base",
  ],
  sans: [
    "sans",
    "sans",
    "saaaans",
    "sans",
    "sans",
    "sans",
    "sans",
    "sans",
    "sans",
    "saaaans",
    "sans",
  ],
  serif: [
    "serif",
    "serif",
    "sair-if",
    "serif",
    "serrif",
    "serif",
    "ser-if",
    "sewif",
    "serif",
    "seeee-riiif",
    "serif",
  ],
  mono: [
    "mono",
    "mono",
    "mo-nooo",
    "mono",
    "mono",
    "mono",
    "mono",
    "mono",
    "mono",
    "moooo-noooo",
    "mono",
  ],
  italic: [
    "italic",
    "italic",
    "ih-tal-ick",
    "italic",
    "italic",
    "italic",
    "i-tal-ic",
    "italic",
    "italic",
    "ih-taaal-iiick",
    "italic",
  ],
  not: [
    "not",
    "not",
    "naaawt",
    "not",
    "not",
    "not",
    "not",
    "nawt",
    "not",
    "naaaawt",
    "not",
  ],
  whitespace: [
    "woihtspace",
    "woightspice",
    "whaaate-spaaace",
    "woightspace",
    "whichtspace",
    "woightspace",
    "wh-ite-space",
    "whitespace",
    "whitespace",
    "whaaaaaht-spaaaace",
    "wite-espace",
  ],
  tracking: [
    "trackin",
    "trackin",
    "traaackin",
    "trackin'",
    "trrackin",
    "trackin",
    "trac-kio",
    "trackin",
    "tracking-eh",
    "traaaack-iiiin'",
    "trackin",
  ],
  tighter: [
    "tahtah",
    "toightah",
    "taaahrt-urrr",
    "toightah",
    "tichtirr",
    "toighther",
    "teieight-yr",
    "tightuh",
    "tighter-eh",
    "taaaaaiiiht-aaaah",
    "tita",
  ],
  wide: [
    "wide",
    "woide",
    "waaahd",
    "woide",
    "wide",
    "woide",
    "wide",
    "wide",
    "wide",
    "waaaahd",
    "wide",
  ],
  wider: [
    "widah",
    "woidah",
    "waaah-durrr",
    "woidah",
    "widirr",
    "woidher",
    "wi-dyr",
    "widuh",
    "wider-eh",
    "waaaah-daaaaah",
    "wida",
  ],
  widest: [
    "widest",
    "woidest",
    "waaah-dest",
    "woidest",
    "widest",
    "woidest",
    "wi-dest",
    "widest",
    "widest",
    "waaaah-deeest",
    "widest",
  ],
  transform: [
    "transform",
    "transform",
    "tranz-foawrm",
    "transform",
    "trrransform",
    "transform",
    "trans-form",
    "transfwam",
    "transform",
    "traaans-foooorm",
    "tranzform",
  ],
  origin: [
    "origin",
    "origin",
    "oar-ih-jin",
    "'origin",
    "origin",
    "origin",
    "o-ri-gin",
    "awigin",
    "origin",
    "oooah-ih-jiiiin",
    "origin",
  ],
  diagonal: [
    "diagonal",
    "diagonal",
    "die-ag-uh-null",
    "diagonal",
    "diagonal",
    "diagonal",
    "di-ag-o-nal",
    "diagonal",
    "diagonal-eh",
    "diiii-aaag-uh-naaaal",
    "diagonal",
  ],
  gpu: [
    "gee-pee-you",
    "gee-pee-you",
    "gee-pee-yewww",
    "gee-pee-you",
    "gee-pee-ye",
    "gee-pee-yeh",
    "gee-pee-you",
    "gee-pee-you",
    "gee-pee-you-eh",
    "geeee-peeee-yuuuou",
    "geepee-u",
  ],
  move: [
    "move",
    "moove",
    "moooove",
    "move",
    "moove",
    "move",
    "move",
    "move",
    "moove",
    "mooooove",
    "move",
  ],
  wait: [
    "wait",
    "wite",
    "waaaait",
    "wait",
    "wait",
    "wait",
    "wait",
    "wait",
    "wait",
    "waaaaait",
    "wait",
  ],
  scrolling: [
    "scrawlin",
    "scrollin",
    "scraaawlin",
    "scrollin'",
    "scroallin",
    "scrollin",
    "scrrol-lio",
    "scrawlin",
    "scrolling-eh",
    "scroooooll-iiiin'",
    "escrollin",
  ],
  events: [
    "events",
    "events",
    "ee-vents",
    "events",
    "events",
    "events",
    "e-vents",
    "events",
    "events",
    "eeee-veeents",
    "events",
  ],
  resize: [
    "resize",
    "resoize",
    "ree-saaahz",
    "resoize",
    "resize",
    "resoize",
    "re-size",
    "resize",
    "resize",
    "reeee-saaaahz",
    "resize",
  ],
  select: [
    "select",
    "select",
    "suh-leeeect",
    "select",
    "select",
    "select",
    "se-lect",
    "select",
    "select",
    "suh-leeeeect",
    "eselect",
  ],
  only: [
    "only",
    "ownly",
    "own-leee",
    "only",
    "only",
    "only",
    "on-ly",
    "only",
    "only",
    "oooown-leeee",
    "onlee",
  ],
  prose: [
    "prose",
    "prose",
    "proooze",
    "prose",
    "prose",
    "prose",
    "prose",
    "prose",
    "prose",
    "prooooose",
    "proze",
  ],
  no: [
    "naw",
    "naur",
    "naaaw",
    "naw",
    "naw",
    "naw",
    "no",
    "naw",
    "no",
    "nooooo",
    "naw",
  ],
  to: [
    "to",
    "too",
    "tuh",
    "to",
    "tae",
    "teh",
    "to",
    "tuh",
    "to",
    "tuuuuh",
    "tuh",
  ],
  from: [
    "frum",
    "frum",
    "fruum",
    "frum",
    "frrum",
    "frum",
    "ffrom",
    "frum",
    "from",
    "fruuuum",
    "frum",
  ],
  via: [
    "via",
    "via",
    "vee-uh",
    "via",
    "via",
    "via",
    "via",
    "via",
    "via",
    "viiii-aaaa",
    "via",
  ],
  box: [
    "box",
    "box",
    "baaawx",
    "box",
    "box",
    "box",
    "box",
    "bawx",
    "box",
    "baaaawx",
    "bawcks",
  ],
  x: [
    "ecks",
    "ecks",
    "eeeecks",
    "ecks",
    "ecks",
    "ecks",
    "ecks",
    "ecks",
    "ecks",
    "eeeeecks",
    "ecks",
  ],
  y: [
    "why",
    "why",
    "whyyy",
    "why",
    "why",
    "why",
    "why",
    "why",
    "why",
    "whyyyy",
    "why",
  ],
  b: [
    "bee",
    "bee",
    "beee",
    "bee",
    "bee",
    "bee",
    "bee",
    "bee",
    "bee",
    "beeeee",
    "bee",
  ],
  l: [
    "ell",
    "ell",
    "ellll",
    "ell",
    "ell",
    "ell",
    "ell",
    "ell",
    "ell",
    "elllll",
    "ell",
  ],
  r: ["ah", "ah", "arrr", "ah", "rrr", "r", "yr", "uh", "ar", "arrrrr", "arr"],
  t: [
    "tee",
    "tee",
    "teee",
    "tee",
    "tee",
    "tee",
    "tee",
    "tee",
    "tee",
    "teeeee",
    "tee",
  ],
  h: [
    "aitch",
    "aitch",
    "aaaitch",
    "'aitch",
    "aitch",
    "aitch",
    "aitch",
    "aitch",
    "aitch",
    "aaaaaitch",
    "aitch",
  ],
  m: ["em", "em", "emmm", "em", "em", "em", "em", "em", "em", "emmmm", "em"],
  p: [
    "pee",
    "pee",
    "peee",
    "pee",
    "pee",
    "pee",
    "pee",
    "pee",
    "pee",
    "peeee",
    "pee",
  ],
  w: [
    "dubble-u",
    "dubble-u",
    "duuuble-yewww",
    "dubble-u",
    "dooble-u",
    "dubble-u",
    "dubble-u",
    "dubble-u",
    "dooble-u",
    "duuuuble-yuuuou",
    "dubble-u",
  ],
  z: [
    "zee",
    "zed",
    "zeeee",
    "zed",
    "zed",
    "zed",
    "zed",
    "zee",
    "zed",
    "zeeeee",
    "zee",
  ],
  fr: [
    "eff-ah",
    "eff-ah",
    "eff-arrr",
    "eff-ah",
    "eff-rrr",
    "eff-r",
    "eff-yr",
    "eff-uh",
    "eff-ar",
    "eeeff-arrrrr",
    "eff-arr",
  ],
  sr: [
    "ess-ah",
    "ess-ah",
    "ess-arrr",
    "ess-ah",
    "ess-rrr",
    "ess-r",
    "ess-yr",
    "ess-uh",
    "ess-ar",
    "eeess-arrrrr",
    "ess-arr",
  ],
};

const DEGENERATE: Record<string, string> = {
  right: "w-wight",
  left: "weft",
  center: "centeww",
  justify: "justifwyyy",
  flex: "fwexx",
  border: "bowdew",
  hover: "h-hoveww",
  order: "owdew",
  overflow: "ovewfwow",
  container: "containyew",
  transparent: "twanspawent",
  opacity: "opaciteeee",
  padding: "p-paddin",
  bottom: "b-b-bottomm",
  top: "t-topp",
  white: "w-wite",
  black: "bwack",
  light: "wight",
  tight: "t-taight",
  through: "fwu",
  stretch: "stwetch",
  shrink: "shwinkk",
  grow: "gwooo",
  between: "b-betweeny",
  around: "awound",
  hidden: "h-hidden",
  visible: "visibwe",
  invisible: "invisibwe",
  absolute: "abso-woot",
  relative: "wewative",
  sticky: "stwickyyy",
  static: "statwic",
  translate: "twanswate",
  rotate: "wotate",
  scale: "scawe",
  shadow: "shadoww",
  outline: "outwine",
  underline: "undewwine",
  uppercase: "uppewcase",
  lowercase: "wowewcase",
  capitalize: "capituwize",
  truncate: "twunkate",
  antialiased: "anti-awiasd",
  placeholder: "pwace-howdew",
  appearance: "appeawance",
  pointer: "pointyew",
  cursor: "cuwsow",
  default: "defauwt",
  allowed: "awwowed",
  screen: "scween",
  scroll: "scwoww",
  overscroll: "ovew-scwoww",
  content: "contentt",
  contents: "contentss",
  separate: "sepawate",
  collapse: "cowwapse",
  reverse: "wevewse",
  divide: "dividee",
  double: "d-doubwe",
  dotted: "dottwed",
  dashed: "dashewd",
  solid: "sowid",
  gradient: "gwadient",
  purple: "puwple",
  orange: "owange",
  yellow: "yewwow",
  indigo: "indigwo",
  pink: "p-pinkk",
  green: "gween",
  blue: "b-bwoo",
  gray: "gway",
  teal: "teaw",
  red: "wed",
  current: "cuwwent",
  cover: "coveww",
  contain: "containy",
  repeat: "wepeat",
  space: "spacee",
  round: "wound",
  linear: "wineaw",
  duration: "duwation",
  delay: "deway",
  transition: "twansishun",
  animate: "animwate",
  bounce: "b-bounce",
  pulse: "puwse",
  spin: "spinn",
  ping: "pingy",
  ease: "eaze",
  none: "n-none",
  auto: "awto",
  fixed: "fiksed",
  local: "wocaw",
  clip: "cwip",
  text: "textt",
  mb: "m-bottom",
  mr: "m-wight",
  mt: "m-topp",
  ml: "m-weft",
  mx: "m-ecksy",
  my: "m-whyyy",
  pb: "p-bottom",
  pr: "p-wight",
  pt: "p-topp",
  pl: "p-weft",
  px: "p-ecksy",
  py: "p-whyyy",
  bg: "b-bg",
  bl: "b-weft",
  br: "b-wight",
  tl: "t-weft",
  tr: "t-wight",
  xs: "exxy",
  sm: "smol",
  md: "mediwum",
  lg: "warge",
  xl: "exx-eww",
  start: "stawt",
  end: "endd",
  evenly: "evenwy",
  wrap: "wwap",
  nowrap: "no-wwap",
  items: "itemss",
  self: "sewf",
  inline: "inwine",
  block: "bwock",
  grid: "gwid",
  flow: "fwow",
  root: "woot",
  row: "wow",
  col: "cow",
  initial: "initiaw",
  focus: "focusss",
  within: "withinny",
  span: "spann",
  gap: "gapp",
  rows: "wows",
  cols: "cows",
  dense: "denseee",
  max: "mawks",
  min: "minny",
  full: "fuww",
  place: "pwace",
  group: "gwoop",
  list: "wist",
  outside: "outsidy",
  lining: "wining",
  nums: "nummies",
  normal: "nowmaw",
  oldstyle: "owd-stywe",
  stacked: "stackwed",
  fractions: "fwacshuns",
  align: "awign",
  clear: "cweaw",
  both: "bof",
  clearfix: "cweaw-fiks",
  float: "fwoat",
  inset: "insett",
  object: "objectt",
  skew: "skyew",
  baseline: "basewine",
  middle: "middwe",
  ring: "wing",
  offset: "offsett",
  inner: "innew",
  fill: "fiww",
  stroke: "stwoke",
  table: "tabwe",
  caption: "capshun",
  cell: "ceww",
  column: "cowumn",
  footer: "footew",
  header: "headdew",
  subpixel: "subpixew",
  break: "bweak",
  words: "wowds",
  all: "aww",
  case: "casee",
  leading: "weadin",
  snug: "snugg",
  relaxed: "wewaxed",
  loose: "woose",
  line: "wine",
  font: "fontt",
  hairline: "haiwwine",
  thin: "thinny",
  medium: "mediwum",
  semibold: "semi-bowd",
  bold: "bowd",
  extrabold: "extwa-bowd",
  extralight: "extwa-wight",
  base: "basee",
  sans: "sansy",
  serif: "sewif",
  mono: "mono",
  italic: "itawic",
  not: "nawt",
  whitespace: "wite-spacee",
  tracking: "twackin",
  tighter: "tightah",
  wide: "widee",
  wider: "widew",
  widest: "widestt",
  transform: "twansfowm",
  origin: "owigin",
  diagonal: "diagonaaw",
  gpu: "gee-pee-yuw",
  move: "mooove",
  wait: "waaait",
  scrolling: "scwowwin",
  events: "eventss",
  resize: "wesize",
  select: "sewect",
  only: "onwy",
  prose: "pwoze",
  no: "n-no",
  to: "tuwu",
  from: "fwom",
  via: "viaaa",
  box: "bawks",
  x: "ecksy",
  y: "whyyy",
  b: "b-bee",
  l: "eww",
  r: "w",
  t: "tee",
  h: "aitch",
  m: "emmm",
  p: "pee",
  w: "d-dubble-u",
  z: "zee",
  fr: "eff-w",
  sr: "ess-w",
};

const EMOJIS: Record<string, string> = {
  right: "➡️",
  left: "⬅️",
  center: "🎯",
  justify: "⚖️",
  flex: "💪",
  border: "🖼️",
  hover: "🛸",
  order: "📋",
  overflow: "🌊",
  container: "📦",
  transparent: "👻",
  opacity: "🌫️",
  padding: "🛋️",
  bottom: "🍑",
  top: "🔝",
  white: "🤍",
  black: "🖤",
  light: "💡",
  tight: "🤏",
  through: "➡️",
  stretch: "🙆",
  shrink: "📉",
  grow: "🌱",
  between: "↔️",
  around: "🔄",
  hidden: "🙈",
  visible: "👁️",
  invisible: "🫥",
  absolute: "👑",
  relative: "👨‍👩‍👧‍👦",
  sticky: "🍯",
  static: "📺",
  translate: "🌐",
  rotate: "🔄",
  scale: "⚖️",
  shadow: "👤",
  outline: "✏️",
  underline: "〰️",
  uppercase: "🔠",
  lowercase: "🔡",
  capitalize: "💰",
  truncate: "✂️",
  antialiased: "✨",
  placeholder: "📌",
  appearance: "🪞",
  pointer: "👆",
  cursor: "🖱️",
  default: "⚙️",
  allowed: "✅",
  screen: "🖥️",
  scroll: "📜",
  overscroll: "📜🌊",
  content: "📄",
  contents: "📑",
  separate: "🪓",
  collapse: "💥",
  reverse: "⏪",
  divide: "➗",
  double: "2️⃣",
  dotted: "🔘",
  dashed: "➖",
  solid: "⬛",
  gradient: "🌈",
  purple: "🟣",
  orange: "🟠",
  yellow: "🟡",
  indigo: "🧿",
  pink: "🩷",
  green: "🟢",
  blue: "🔵",
  gray: "🩶",
  teal: "🦚",
  red: "🔴",
  current: "⚡",
  cover: "🛏️",
  contain: "📥",
  repeat: "🔁",
  space: "🚀",
  round: "⭕",
  linear: "📏",
  duration: "⏱️",
  delay: "⏳",
  transition: "🔀",
  animate: "🎬",
  bounce: "🏀",
  pulse: "💓",
  spin: "🌀",
  ping: "🏓",
  ease: "😌",
  none: "🚫",
  auto: "🚗",
  fixed: "📌",
  local: "🏠",
  clip: "📎",
  text: "📝",
  mb: "⬇️",
  mr: "➡️",
  mt: "⬆️",
  ml: "⬅️",
  mx: "↔️",
  my: "↕️",
  pb: "⬇️",
  pr: "➡️",
  pt: "⬆️",
  pl: "⬅️",
  px: "↔️",
  py: "↕️",
  bg: "🎨",
  bl: "↙️",
  br: "↘️",
  tl: "↖️",
  tr: "↗️",
  xs: "🐜",
  sm: "🐭",
  md: "📦",
  lg: "🐘",
  xl: "🐋",
  start: "🏁",
  end: "🔚",
  evenly: "🟰",
  wrap: "🌯",
  nowrap: "🚫🌯",
  items: "🧺",
  self: "🪞",
  inline: "➖",
  block: "🧱",
  grid: "#️⃣",
  flow: "🌊",
  root: "🌳",
  row: "🚣",
  col: "🏛️",
  initial: "🔠",
  focus: "🔍",
  within: "📥",
  span: "🌉",
  gap: "🕳️",
  rows: "🚣🚣",
  cols: "🏛️🏛️",
  dense: "🧱",
  max: "📈",
  min: "📉",
  full: "💯",
  place: "📍",
  group: "👥",
  list: "📋",
  outside: "🚪",
  lining: "🧵",
  nums: "🔢",
  normal: "😐",
  oldstyle: "👴",
  stacked: "🥞",
  fractions: "🍕",
  align: "📐",
  clear: "🧼",
  both: "✌️",
  clearfix: "🧼🔧",
  float: "🎈",
  inset: "📥",
  object: "📦",
  skew: "📐",
  baseline: "🎵",
  middle: "🎯",
  ring: "💍",
  offset: "↪️",
  inner: "🫀",
  fill: "🪣",
  stroke: "🖌️",
  table: "🪑",
  caption: "💬",
  cell: "📱",
  column: "🏛️",
  footer: "🦶",
  header: "🧠",
  subpixel: "🔬",
  break: "💔",
  words: "💬",
  all: "🌐",
  case: "💼",
  leading: "🎬",
  snug: "🛏️",
  relaxed: "😎",
  loose: "🪿",
  line: "➖",
  font: "🔤",
  hairline: "💇",
  thin: "🥢",
  medium: "🥩",
  semibold: "🏋️",
  bold: "💪",
  extrabold: "🦾",
  extralight: "🪶",
  base: "⚾",
  sans: "🚫",
  serif: "🤠",
  mono: "🐒",
  italic: "🇮🇹",
  not: "⛔",
  whitespace: "⬜",
  tracking: "📦",
  tighter: "🤏",
  wide: "↔️",
  wider: "↔️↔️",
  widest: "↔️↔️↔️",
  transform: "🤖",
  origin: "🥚",
  diagonal: "↗️",
  gpu: "🎮",
  move: "🚚",
  wait: "⌛",
  scrolling: "📜",
  events: "🎫",
  resize: "↔️",
  select: "☑️",
  only: "1️⃣",
  prose: "📖",
  no: "🚫",
  to: "➡️",
  from: "⬅️",
  via: "🛣️",
  box: "📦",
  x: "❌",
  y: "❓",
  b: "🅱️",
  l: "🦵",
  r: "➡️",
  t: "🍵",
  h: "🏨",
  m: "Ⓜ️",
  p: "🅿️",
  w: "〰️",
  z: "💤",
  fr: "🇫🇷",
  sr: "♿",
};

export function specialFor(word: string, dialect: DialectId): string | null {
  if (dialect === "emojis" && EMOJIS[word]) {
    return EMOJIS[word];
  }
  if (dialect === "degenerate" && DEGENERATE[word]) {
    return DEGENERATE[word];
  }
  if (
    dialect === "yorkshire" ||
    dialect === "newzealand" ||
    dialect === "jamaica" ||
    dialect === "appalachia" ||
    dialect === "geordie"
  ) {
    return null;
  }
  const row = ROWS[word];
  if (!row) {
    return null;
  }
  const index = DIALECT_IDS.indexOf(dialect);
  if (index < 0 || !row[index]) {
    return null;
  }
  return row[index];
}
